# This is a basic workflow that is manually triggered

name: Merge release

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      required-labels:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Merge label'
        # Default value if no value is explicitly provided
        default: 'release'
        # Input has to be provided for the workflow to run
        required: true
      pull-request:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'PR name'
        # Default value if no value is explicitly provided
        default: 'release'
        # Input has to be provided for the workflow to run
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - uses: reitermarkus/automerge@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash
          do-not-merge-labels: never-merge
          required-labels: release
          pull-request: ${{ github.event.inputs.pull-request }}
          dry-run: true
